# check status of sagemaker endpoint being deployed
aws sagemaker describe-endpoint --endpoint-name nv-embedqa-e5-v5-endpoint

# check if cloudwatch log group exists
aws logs describe-log-groups --log-group-name-prefix "//aws/sagemaker/Endpoints"

# check endpoint's failure reason
aws sagemaker describe-endpoint --endpoint-name nv-embedqa-e5-v5-endpoint
