# create key pair for ssh
aws ec2 create-key-pair \
  --key-name vector-db-key \
  --query 'KeyMaterial' \
  --output text > vector-db-key.pem

chmod 400 vector-db-key.pem

# create security group 
aws ec2 create-security-group \
  --group-name vector-db-sg \
  --description "Security group for FastAPI Vector DB"

#
aws ec2 authorize-security-group-ingress --group-name vector-db-sg \
  --protocol tcp --port 22 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name vector-db-sg \
  --protocol tcp --port 8001 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name vector-db-sg \
  --protocol tcp --port 8002 --cidr 0.0.0.0/0

# 5)
aws ec2 describe-images \
  --owners 099720109477 \
  --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
  --query 'Images[*].[ImageId,Name]' \
  --output text | sort -k2 | tail -n 1


# launch EC2 instance
aws ec2 run-instances \
  --image-id ami-03c1f788292172a4e \
  --instance-type t3.medium \
  --key-name vector-db-key \
  --security-groups vector-db-sg \
  --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":30,"VolumeType":"gp3"}}]' \
  --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=vector-db-server}]' \
  --query 'Instances[0].InstanceId' \
  --output text

# wait until instance is running
aws ec2 wait instance-running --instance-ids i-020bd6a303731e6b9

aws ec2 describe-instances \
  --instance-ids i-020bd6a303731e6b9 \
  --query "Reservations[0].Instances[0].PublicIpAddress" \
  --output text

  

ssh -i vector-db-key.pem ubuntu@54.71.36.176


sudo apt update && sudo apt upgrade -y
sudo apt install python3 python3-pip docker.io git -y
sudo systemctl start docker
sudo systemctl enable docker
